safe:        true
source:      .
destination: ./_site
plugins_dir: ./_plugins
future:      true
lsi:         false
higlighter:  pygments
markdown:    kramdown

exclude: [Gemfile]

collections:
  unix-git:
    output: true
  ghc12:
    output: true

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  syntax_highlighter_opts:
    css_class: 'style'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
