# Site Settings

title: Elsa Gonsiorowski
url: "http://gonsie.com"

# Author Info

author: Elsa Gonsiorowski
email: gonsie@me.com
github_username: gonsie

# accent settings

copyright: accent
intro: false

# Build settings

permalink: /blorg/:slug:output_ext
markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jekyll-feed

feed:
    path: blorg/feed.xml


# old site

collections:
  unix-git:
    output: true
  ghc12:
    output: true

defaults:
  - scope:
      type: tag
    values:
      layout: rss-gen
